# Generated by Django 2.2.13 on 2022-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_choice',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'SportWear'), ('OW', 'Out Wear')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label_choice',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('d', 'danger')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
