# Generated by Django 2.2.13 on 2022-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='jjdjdjdjdjdjdv'),
            preserve_default=False,
        ),
    ]
